# Generated by Django 5.0.3 on 2024-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('url', models.URLField()),
                ('short_url', models.URLField()),
                ('lifetime', models.TimeField()),
                ('visibility', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=15)),
            ],
        ),
    ]
