# Generated by Django 5.0.3 on 2024-03-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=15),
        ),
    ]
