# Generated by Django 5.0.3 on 2024-03-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0003_link_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='lifetime',
            field=models.DateTimeField(),
        ),
    ]
